open Js_of_ocaml
open Ezjs_ace

open Compiler_utils
open Compiler_options

(* [modname] is the module name, [source_f] is the source file *)
let compile_program modname source =

  print_endline "compile ?";

  (* input/output channels *)
  let lexbuf = Lexing.from_string source in

  print_endline "lexing";

  let log_c = stdout in


  try
    (* Activates passes according to the backend used *)
    Mls2seq.load_conf ();
    print_endline "conf";
    (* Process the [lexbuf] to an Heptagon AST *)
    let p = Hept_parser_scoper.parse_program modname lexbuf log_c in
    print_endline "parsing";
    (* Process the Heptagon AST *)
    let p = Hept_compiler.compile_program p log_c in
    (* Compile Heptagon to MiniLS *)
    let p = do_pass "Translation into MiniLS"
        Hept2mls.program p (Mls_compiler.pp log_c) in
    print_endline "OK";
    (* (\* Output the .mls *\) *)
    (*   do_silent_pass "MiniLS serialization" (fun () -> Mls_printer.print mls_c p) (); *)
    (* Process the MiniLS AST *)
    let p = Mls_compiler.compile_program p log_c in
    (* Generate the sequential code *)
    Mls2seq.program p log_c;

    (* close_out log_c; *)
  with e -> raise e (* close_out log_c; raise e *)


let compile source =
  let modname = "tryheptc" in
  let modul = Names.modul_of_string modname in
  Initial.initialize modul;
  compile_program modname source

(** Show an error with [text] at [loc] in the console as well as the editor *)
(* let show_error editor ?(in_console=false) text loc = *)
(*   if in_console then *)
(*     Page.Console.error (Printf.sprintf "%s at %s" text (Lexing.string_of_loc loc)); *)

(*   let s_row = loc.ast_lnum and s_col = loc.ast_cnum in *)

(*   Ace.set_mark *)
(*     ~type_:Ace.Error *)
(*     ~loc:{ loc_start = (s_row, s_col); loc_end = (s_row, s_col) } *)
(*     editor text *)

let print_error text =
  Page.Console.error text

(** Incremental parser to reparse the token stream and generate an
    error message (the verified and extracted parser does not
    generate error messages). Adapted directly from menhir's
    calc-incremental example. *)

(** Read the fake file generated by printers *)
let read_file filename =
  let ch = open_in filename in
  let s = really_input_string ch (in_channel_length ch) in
  close_in ch;
  s

exception CompileError

(** Compile the program for visualisation purposes *)
let compile_and_exn editor ?(in_console=false) step =
  (* Reset markers *)
  Ace.clear_marks editor;

  try
    compile (Ace.get_contents editor)
  with e -> print_error (Printexc.to_string e)

  (* (try *)
  (*    (lex_and_parse_program editor ~in_console () *)
  (*     |> (fun decls -> *)
  (*         if step = Page.Source then raise Veluslib.Done; *)
  (*         match Velus.compile decls (get_main_node decls) with *)
  (*         | Error errmsg -> *)
  (*           Format.fprintf Format.str_formatter "%a\n" Driveraux.print_error errmsg; *)
  (*           print_error (Format.flush_str_formatter ()); *)
  (*           raise CompileError *)
  (*         | OK _ -> ())); *)
  (*  with *)
  (*  | Veluslib.Done -> ()) *)

let compile_and_output editor panel =
  (* Reset destinations *)
  (* Veluslib.reset_config (); *)

  (* Page.(match panel.ptype with *)
  (*     | Source -> () *)
  (*     | NoLast -> Veluslib.nolast_destination := Some "out" *)
  (*     | NoSwitch -> Veluslib.noswitch_destination := Some "out" *)
  (*     | NoLocal -> Veluslib.nolocal_destination := Some "out" *)
  (*     | Lustre -> Veluslib.lustre_destination := Some "out" *)
  (*     | NLustre -> *)
  (*       Veluslib.nlustre_destination := Some "out"; *)
  (*       Veluslib.dce := get_checkbox_value "Dead Code Elimination" panel.controls; *)
  (*       Veluslib.dupregrem := get_checkbox_value "Remove Duplicate Registers" panel.controls *)
  (*     | Stc -> *)
  (*       if (get_checkbox_value "Schedule" panel.controls) *)
  (*       then Veluslib.sch_destination := Some "out" *)
  (*       else Veluslib.stc_destination := Some "out" *)
  (*     | Obc -> *)
  (*       Veluslib.obc_destination := Some "out"; *)
  (*       Veluslib.fuse_obc := get_checkbox_value "Fusion" panel.controls; *)
  (*       Veluslib.normalize_switches := get_checkbox_value "Normalize Switches" panel.controls *)
  (*     | Clight -> PrintClight.destination := Some "out" *)
  (*   ); *)

  compile_and_exn editor ~in_console:true Page.(panel.ptype);
  Ace.set_contents panel.editor (read_file "out")

let _ =
  (* add_target_language "obc"; *)
  (* Js_of_ocaml.Sys_js.mount ~path:"pervasives.epci" (fun ~prefix ~path -> None); *)
  Js_of_ocaml.Sys_js.create_file ~name:"pervasives.epci" ~content:"";
  (* Comment charger le fichier pervasives.epci ? *)

  let editor_panel = Page.(create_panel Source
      [("+Mls", Button (fun () -> ignore (create_panel Lustre [])));
       ("+Obc", Button (fun () -> ignore (create_panel Clight [])))
      ])
  in
  Page.add_panel_control editor_panel ("Compile", Page.Button (fun () ->
      try List.iter (fun p -> compile_and_output editor_panel.editor p) !Page.output_panels
      with _ -> ()
    ));
  editor_panel.editor.editor##on (Js.string "change") (fun () ->
      Page.save_program (Ace.get_contents editor_panel.editor);
      try compile_and_exn editor_panel.editor Page.Source
      with _ -> ());
  Ace.set_contents editor_panel.editor (Page.get_saved_program ())
